config/routes.rb
Rails.application.routes.draw do
  
  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  root :to => 'home#index'

  resources :themes

  post 'webhooks/app/uninstalled' => 'webhooks#app/uninstalled'
  post 'webhooks/shop/updated'    => 'webhooks#shop_updated'
  

end

app/models/session_storage.rb
class SessionStorage
  def self.store(session)
    shop = Shop.find_or_initialize_by(shopify_domain: session.url)
    shop.shopify_token = session.token
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    return unless id
    shop = Shop.find(id)
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  after_create :init_webhooks

  def init_webhooks
    shopify_session
   
    topics = ["app/uninstalled", "shop/update"]

    topics.each do |topic|
      ShopifyAPI::Webhook.create(:format => "json", :topic => topic, :address => "https://natparksdev.pagekite.me/webhooks/#{topic}")
    end
  end

  def shopify_session
    shop_session = ShopifyAPI::Session.new(self.shopify_domain, self.shopify_token)
    ShopifyAPI::Base.activate_session(shop_session)
  end
end

app/models/theme.rb
class Theme < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ShopifyApp::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  layout ShopifyApp.configuration.embedded_app? ? 'embedded_app' : 'application'
end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController
  def index
    @themes = ShopifyAPI::Theme.find(:all, :params => {:limit => 10})
    @theme_id = params[:theme_id]
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
    #@theme_id = params[:theme_id]
  end

  def update
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ShopifyApp::SessionsController
end

app/controllers/themes_controller.rb
class ThemesController < AuthenticatedController
  def index
    theme_id = params[:theme_id]
    Dir.foreach('public/theme_files/assets') do |filename|
      next if filename == '.' or filename == '..'
      file = File.open("public/theme_files/assets/#{filename}", "rb")
      contents = file.read
      asset = ShopifyAPI::Asset.new(:theme_id => theme_id)
      asset.theme_id = theme_id
      if filename.match(/^.*\.liquid/)
        asset.value = contents
      else
        asset.attach(contents)
      end
      asset.key = "assets/#{filename}"
      asset.save
    end
    Dir.foreach('public/theme_files/templates') do |filename|
      next if filename == '.' or filename == '..'
      file = File.open("public/theme_files/templates/#{filename}", "rb")
      contents = file.read
      asset = ShopifyAPI::Asset.new(:theme_id => theme_id)
      asset.theme_id = theme_id
      if filename.match(/^.*\.liquid/)
        asset.value = contents
      else
        asset.attach(contents)
      end
      asset.key = "templates/#{filename}"
      asset.save
    end
    redirect_to controller: 'home', action: 'index', theme_id: theme_id
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end
       
  def update
  end
     
  def destroy
  end
           
end

app/controllers/webhook_controller.rb
class WebhookController < AuthenticatedController

  skip_before_filter :verify_authenticity_token

  def app_uninstalled
    themes = ShopifyAPI::Theme.find(:all)
    themes.each do |theme|
      Dir.foreach('public/theme_files/assets') do |filename|
        next if filename == '.' or filename == '..'
        asset = ShopifyAPI::Asset.find(:all, :params => {:key => "assets/#{filename}", :theme_id => theme})
        asset.destroy
      end
      Dir.foreach('public/theme_files/templates') do |filename|
        next if filename == '.' or filename == '..'
        asset = ShopifyAPI::Asset.find(:all, :params => {:key => "templates/#{filename}", :theme_id => theme})
        asset.destroy
      end
    end
    shop = Shop.find_by_shopify_domain(ShopifyAPI::Shop.current.domain)
    shop.destroy
  end

  def shop_updated
  end

  private

  def verify_webhook
    data = request.body.read.to_s
    #hmac_header = request.headers['HTTP_X_SHOPIFY_HMAC_SHA256']
    digest  = OpenSSL::Digest::Digest.new('sha256')
    calculated_hmac = Base64.encode64(OpenSSL::HMAC.digest(digest, SyncApp::Application.config.shopify.secret, data)).strip
    unless calculated_hmac == hmac_header
      head :unauthorized
    end
    
    request.body.rewind
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/home/index.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Home",
      icon: "<%= asset_path('faveicon.png') %>"
    });
  });
</script>
<table class="table table-hover">
  <thead>
    <tr>
      <th>
        #
      </th>
      <th>
        Themes
      </th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% num = 0 %>
    <% @themes.each do |theme| %>
      <% num += 1 %>
      <tr>
        <td>
          <%= num %>
        </td>
        <td>
          <%= link_to theme.name, themes_path(:theme_id => theme.id), :id => "theme-#{num}" %>
        </td>
        <th>
          <% if theme.id.to_s == @theme_id %>
            Files Loaded
          <% end %>
        </th>
        <td>
          <div class="sk-fading-circle" id="load-<%= num %>" style="display: none">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= javascript_tag do %>
  window.blahURL = "<%=j themes_path %>"
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductTemplates</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shopify Embedded Example App</title>

  <script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: "<%= ShopifyApp.configuration.api_key %>",
      shopOrigin: '<%= "https://#{ @shop_session.url }" if @shop_session %>'
    });
  </script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>
  <%= yield %>
</body>
</html>

app/views/themes/index.html.erb
<h3>Files Loaded</h3>
<% Dir.foreach('public/theme_files/assets') do |filename| %>
  <% next if filename == '.' or filename == '..' %>
  <% file = File.open("public/theme_files/assets/#{filename}", "rb") %>
  <% contents = file.read %>
  <% asset = ShopifyAPI::Asset.new(:theme_id => @theme_id) %>
  <% asset.theme_id = @theme_id %>
  <% if filename.match(/^.*\.liquid/) %>
    <% asset.value = contents %>
  <% else %>
    <% asset.attach(contents) %>
  <% end %>
  <% asset.key = "assets/#{filename}" %>
  <% asset.save %>
<% end %>
<% Dir.foreach('public/theme_files/templates') do |filename| %>
  <% next if filename == '.' or filename == '..' %>
  <% file = File.open("public/theme_files/templates/#{filename}", "rb") %>
  <% contents = file.read %>
  <% asset = ShopifyAPI::Asset.new(:theme_id => @theme_id) %>
  <% asset.theme_id = @theme_id %>
  <% if filename.match(/^.*\.liquid/) %>
    <% asset.value = contents %>
  <% else %>
    <% asset.attach(contents) %>
  <% end %>
  <% asset.key = "templates/#{filename}" %>
  <% asset.save %>
<% end %>